-- 0009 – a 22 alapkategória
--
-- A kategóriák backendből konfigurálhatók: új kategória hozzáadásához nem kell
-- alkalmazásfrissítés. Az `icon` egy emoji (a kategóriajelvényeken jelenik meg),
-- a `color` a keréken megjelenő szín.

insert into public.categories (slug, name, description, icon, color, is_hungarian, sort_order)
values
  -- ───────── magyar fókuszú kategóriák ─────────
  ('magyar-tortenelem', 'Magyar történelem',
   'Honfoglalástól a rendszerváltásig: királyok, csaták, korszakok.',
   '👑', '#B23A48', true, 10),
  ('magyar-irodalom', 'Magyar irodalom',
   'Költők, regények, szereplők, idézetek, évszámok.',
   '📖', '#8E5572', true, 20),
  ('magyar-kultura', 'Magyar kultúra',
   'Hagyományok, népszokások, találmányok, hétköznapi műveltség.',
   '🎭', '#C77D3A', true, 30),
  ('magyar-foldrajz', 'Magyar földrajz',
   'Megyék, városok, folyók, tavak, hegyek, nemzeti parkok.',
   '🗺️', '#3E7C59', true, 40),
  ('magyar-kozelet', 'Magyar közélet',
   'Államszervezet, jelképek, intézmények – tényszerű általános műveltség.',
   '🏛️', '#5A6B8C', true, 50),
  ('magyar-sport', 'Magyar sport',
   'Olimpiai bajnokok, aranycsapat, klubok, rekordok.',
   '🏃', '#2E7D9A', true, 60),
  ('magyar-zene-film', 'Magyar zene és film',
   'Zeneszerzők, előadók, filmek, rendezők, díjak.',
   '🎬', '#9B4DCA', true, 70),
  ('magyar-nyelv', 'Magyar nyelv',
   'Helyesírás, nyelvtan, szólások, jelentések, nyelvtörténet.',
   '🔤', '#A8703A', true, 80),

  -- ───────── általános kategóriák ─────────
  ('vilagtortenelem', 'Világtörténelem',
   'Ókortól a 20. századig: birodalmak, uralkodók, fordulópontok.',
   '🏺', '#7A5C3E', false, 110),
  ('foldrajz', 'Földrajz',
   'Országok, fővárosok, hegyek, óceánok, rekordok.',
   '🌍', '#2F7F8C', false, 120),
  ('tudomany', 'Tudomány',
   'Fizika, kémia, biológia, matematika, csillagászat.',
   '🔬', '#3C6EBF', false, 130),
  ('technologia', 'Technológia',
   'Számítástechnika, internet, mérnöki megoldások, találmányok.',
   '💻', '#4B5563', false, 140),
  ('allatvilag', 'Állatvilág',
   'Emlősök, madarak, halak, rovarok – élőhelyek és rekordok.',
   '🦊', '#6B8E23', false, 150),
  ('termeszet', 'Természet',
   'Növények, éghajlat, ökoszisztémák, természeti jelenségek.',
   '🌿', '#3F8F5B', false, 160),
  ('sport', 'Sport',
   'Világbajnokságok, olimpiák, sportágak szabályai, legendák.',
   '⚽', '#1F7A8C', false, 170),
  ('film-sorozat', 'Filmek és sorozatok',
   'Klasszikusok, rendezők, szereplők, díjak.',
   '🍿', '#B5446E', false, 180),
  ('zene', 'Zene',
   'Klasszikus és populáris zene, előadók, hangszerek.',
   '🎵', '#8A5CF6', false, 190),
  ('irodalom', 'Irodalom',
   'Világirodalmi művek, szerzők, korszakok.',
   '📚', '#7C5CFF', false, 200),
  ('muveszet', 'Művészet',
   'Festészet, szobrászat, építészet, stílusok.',
   '🎨', '#D97706', false, 210),
  ('etel-ital', 'Étel és ital',
   'Konyhák, alapanyagok, italok, gasztronómiai fogalmak.',
   '🍽️', '#C2410C', false, 220),
  ('erdekessegek', 'Érdekességek',
   'Vegyes tudnivalók, rekordok, kevéssé ismert tények.',
   '✨', '#0EA5A4', false, 230),
  ('logika', 'Logika és fejtörők',
   'Számsorok, következtetés, klasszikus fejtörők.',
   '🧩', '#6366F1', false, 240)
on conflict (slug) do update
  set name = excluded.name,
      description = excluded.description,
      icon = excluded.icon,
      color = excluded.color,
      is_hungarian = excluded.is_hungarian,
      sort_order = excluded.sort_order;
